//
//  Monsters.h
//  MasmorraDados
//
//  Created by Marlon Andrade on 6/7/15.
//
//

#ifndef MasmorraDados_Monsters_h
#define MasmorraDados_Monsters_h

#define ATTACK_MONSTER_MINOR_GOBLIN        1
#define DEFENSE_MONSTER_MINOR_GOBLIN       2
#define EXPERIENCE_MONSTER_MINOR_GOBLIN    2

#define ATTACK_MONSTER_MINOR_CULTISTA      2
#define DEFENSE_MONSTER_MINOR_CULTISTA     2
#define EXPERIENCE_MONSTER_MINOR_CULTISTA  2

#define ATTACK_MONSTER_MINOR_ESQUELETO     2
#define DEFENSE_MONSTER_MINOR_ESQUELETO    2
#define EXPERIENCE_MONSTER_MINOR_ESQUELETO 2

#define ATTACK_MONSTER_MINOR_ORC           3
#define DEFENSE_MONSTER_MINOR_ORC          2
#define EXPERIENCE_MONSTER_MINOR_ORC       2

#define ATTACK_MONSTER_MINOR_ARANHA        2
#define DEFENSE_MONSTER_MINOR_ARANHA       4
#define EXPERIENCE_MONSTER_MINOR_ARANHA    3

#define ATTACK_MONSTER_MINOR_CARNICAL      3
#define DEFENSE_MONSTER_MINOR_CARNICAL     2
#define EXPERIENCE_MONSTER_MINOR_CARNICAL  3

#endif
