//
//  Monsters.h
//  SurvivalDungeon
//
//  Created by Marlon Andrade on 6/7/15.
//
//

#ifndef SurvivalDungeon_Monsters_h
#define SurvivalDungeon_Monsters_h

#define ATTACK_MONSTER_MINOR_RAT        1
#define DEFENSE_MONSTER_MINOR_RAT       2
#define EXPERIENCE_MONSTER_MINOR_RAT    2

#define ATTACK_MONSTER_MINOR_FROG      2
#define DEFENSE_MONSTER_MINOR_FROG     2
#define EXPERIENCE_MONSTER_MINOR_FROG  2

#define ATTACK_MONSTER_MINOR_BEE     2
#define DEFENSE_MONSTER_MINOR_BEE    2
#define EXPERIENCE_MONSTER_MINOR_BEE 2

#define ATTACK_MONSTER_MINOR_SCORPION           3
#define DEFENSE_MONSTER_MINOR_SCORPION          2
#define EXPERIENCE_MONSTER_MINOR_SCORPION       2

#define ATTACK_MONSTER_MINOR_SPIDER        2
#define DEFENSE_MONSTER_MINOR_SPIDER       4
#define EXPERIENCE_MONSTER_MINOR_SPIDER    3

#define ATTACK_MONSTER_MINOR_MAMMOTH      3
#define DEFENSE_MONSTER_MINOR_MAMMOTH     2
#define EXPERIENCE_MONSTER_MINOR_MAMMOTH  3

#endif
